name: Tests (latest)

on:
  push:
    branches: [ backport-java11 ]
  pull_request:
    branches: [ backport-java11 ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up java
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven

      - name: Build and Test with Maven
        run: mvn clean test
